export const VIEW_ALL_PROBLEMS = 'VIEW_ALL_PROBLEMS';
export const ADD_PROBLEM = 'ADD_PROBLEM';
export const VIEW_ONE_PROBLEM_AND_SOLUTIONS = 'VIEW_ONE_PROBLEM_AND_SOLUTIONS';
export const ADD_SOLUTION = 'ADD_SOLUTION';
export const UPDATE_SOLUTION = 'UPDATE_SOLUTION';
export const DELETE_SOLUTION = 'DELETE_SOLUTION';
